### ISSUE TITLE
Can jdeb make empty directories?

### ISSUE THREAD

**Issue by Kam5FCC** [tcurdt/jdeb#189] opened 2014-12-12 00:27 UTC
In my maven project I've got:
````    
    <data>
        <type>template</type>
        <paths>
            <path>/myDir/log</path>
       </paths>
    </data>
````
and I get this
````
     kevin@Sandbox:~$ ll /myDir/
     total 24
     drw-r--r-- 2 kevin kevin 4096 Dec 11  2014 log/
     kevin@Sandbox:~$ ll /myDir/log/
     ls: cannot access /myDir/log/.: Permission denied
     ls: cannot access /myDir/log/..: Permission denied
     total 0
     d????????? ? ? ? ?            ? ./
     d????????? ? ? ? ?            ? ../
````

Am I doing this wrong or is it not permissable to create empty directories with deb files?

Thanks,
Kevin

**Comment by tcurdt** [comment] 2015-01-29 20:23
Can this be closed now?

**Comment by tcurdt** [comment] 2015-02-09 14:35
@Kam5FCC I assume this was a user error and close it for now. Let me know if you still have problems.

**Closed by tcurdt** 2015-02-09 14:35 UTC
Labels: question, waiting for feedback

**Comment by nikhil-bidgely** [comment] 2018-11-30 18:52
@tcurdt I tried the following:
<data>
   <type>template</type>
   <paths>
       <path>/var/${packageName}/temp</path>
   </paths>
   <mapper>
	   <type>perm</type>
	   <prefix>/var/${packageName}/temp</prefix>
	   <user>${userName}</user>
	   <group>${groupName}</group>
	   <dirmode>775</dirmode>
   </mapper>
</data>

still the permissions for /var/${packageName}/temp are drwxr-xr-x (instead of drwxrwxr-x), can you please let me know what is that I've done wrong?
Also, inside /var/${packageName}/temp, I see _**var**_ it's like there's a circular loop of dirs.

**Comment by tcurdt** [comment] 2018-11-30 20:30
Maybe read through this #273  and let me know if that helps to clear things up. Not sure about the circular loop though - that needs some more details.

**Comment by bzzy** [comment] 2019-03-13 09:37
Hello, 

Maybe an infromation from my comment could help to figure out with the templates problem.

I created a simple maven java application with the jdeb plugin of version 1.7. I put a data section with a template type:
```xml
<data>
	<type>template</type>
	<paths>
		<path>var/log/${project.artifactId}</path>
		<path>var/run/${project.artifactId}</path>                                        
	</paths>
	<mapper>
		<type>perm</type>
		<user>loader</user>
		<group>loader</group>
		<filemode>750</filemode>
	</mapper>
</data>
```

After build I saw lines as below in the log:
```
dir: .//var/log/***/
dir: .//var/run/***/
```
I thought that paths are strange. So I digged a little bit in the sources of the jdeb (master) and found that if the mapper is used then following code executes in the AbstractDataProducer:
```
fileEntry = map(fileEntry);
```
and then in the PermMapper.map():
```
entry.setName(Utils.joinUnixPath(
                prefix,
                Utils.stripPath(strip, entry.getName()
                )));
```
Looks like the problem is in using of joinUnixPath here. Maybe it will be better to put some checks here and use joinPath with a separator when the prefix is not defined.

By the way, when there is no the mapper section in the data section then no problems with the paths.

Kind regards.

**Comment by tcurdt** [comment] 2019-03-13 09:50
@bzzy thanks for you comment but I am not sure I understand I fully understand.

You are concerned about the `.//` in the `.//var/log/***/` which is there because you are not setting the prefix? Which I agree should be improved.

I am wondering about the `***` though. Or did you just shorten the output?

**Comment by bzzy** [comment] 2019-03-13 10:05
@tcurdt you are right. I forgot to note that I shorten the output.
