### ISSUE TITLE
Unable to specify custom control directory: The 'control' attribute doesn't point to a directory

### ISSUE THREAD

**Issue by ieugen** [tcurdt/jdeb#178] opened 2014-07-30 10:36 UTC
Hello,

I think I've stumbled across a bug in JDEB. I have a requirement to build multiple deb's in one project (Apache Syncope) and to do this I have to have multiple control directories. 

So I've renamed one control  directory and placed this in jdeb config: 
~~~
  <controlDir>${project.basedir}/src/core/control</controlDir>
~~~  
However, the build fails with the following message:
~~~
org.vafer.jdeb.PackagingException: The 'control' attribute doesn't point to a directory
~~~
Enabling the debug output got me this: 
~~~
Configuring mojo 'org.vafer:jdeb:1.3:jdeb' with basic configurator -->
[DEBUG]   (f) attach = true
[DEBUG]   (f) baseDir = /home/ieugen/contracte/samples/syncope/deb
[DEBUG]   (f) buildDirectory = /home/ieugen/contracte/samples/syncope/deb/target
[DEBUG]   (f) changesIn = [[baseDir]]/CHANGES.txt
[DEBUG]   (f) changesOut = [[buildDir]]/[[artifactId]]_[[version]]_all.changes
[DEBUG]   (f) changesSave = [[baseDir]]/CHANGES.txt
[DEBUG]   (f) compression = gzip
[DEBUG]   (f) controlDir = [[baseDir]]/src/deb/control
[DEBUG]   (f) deb = [[buildDir]]/[[artifactId]]_[[version]]_all.[[extension]]
[DEBUG]   (f) installDir = /opt/[[artifactId]]
[DEBUG]   (f) project = MavenProject: org.apache.syncope:debian:1.3.0-SNAPSHOT @ /home/ieugen/contracte/samples/syncope/deb/pom.xml
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@48de8ca
[DEBUG]   (f) settings = org.apache.maven.execution.SettingsAdapter@606e685a
[DEBUG]   (f) signCfgPrefix = jdeb.
[DEBUG]   (f) signMethod = debsig-verify
[DEBUG]   (f) signPackage = false
[DEBUG]   (f) signRole = origin
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipPOMs = true
[DEBUG]   (f) skipSubmodules = false
[DEBUG]   (f) snapshotEnv = SNAPSHOT
[DEBUG]   (f) snapshotExpand = false
[DEBUG]   (f) submodules = true
[DEBUG]   (f) type = deb
[DEBUG]   (f) verbose = false
[DEBUG] -- end configuration --
~~~

You can try the build at: [https://github.com/ieugen/syncope/tree/single-deb-project](https://github.com/ieugen/syncope/tree/single-deb-project)

**Comment by tcurdt** [comment] 2015-02-15 12:00
since it's there was a "works for me" I am closing this for now. please let us know if there still is problem, @ieugen

**Comment by rfletcher** [comment] 2015-02-27 18:47
I have the issue using 1.4 as was originally reported. When my control dir is the default it works as expected, but after renaming the "deb" portion to "foo" and configuring this way:

````xml
<plugin>
    <artifactId>jdeb</artifactId>
    <groupId>org.vafer</groupId>
    <version>1.4</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>jdeb</goal>
            </goals>
            <configuration>
                <controlDir>${basedir}/src/foo/control</controlDir>
...
````

I get:

````
org.vafer.jdeb.PackagingException: The 'control' attribute doesn't point to a directory.
	at org.vafer.jdeb.DebMaker.validate(DebMaker.java:220)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:551)
````

I don't know what env. information might be helpful to you, but please ask. Here's a little bit of info, courtesy of Maven:

````
$ mvn --version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T12:29:23-05:00)
Maven home: /usr/local/Cellar/maven/3.2.5/libexec
Java version: 1.7.0_67, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.2", arch: "x86_64", family: "mac"
````

**Comment by tcurdt** [comment] 2015-02-27 19:18
We should improve the error message to give a path here https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DebMaker.java#L220

And this was working with 1.3.1 or not?

**Comment by rfletcher** [comment] 2015-02-28 18:02
Maven couldn't find 1.3.1 to download. Is it in a different repository?

It does fail with 1.3:

````
org.vafer.jdeb.PackagingException: The 'control' attribute doesn't point to a directory.
	at org.vafer.jdeb.DebMaker.validate(DebMaker.java:222)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:531)
````

**Comment by tcurdt** [comment] 2015-02-28 18:26
Ups - sorry. I meant 1.3.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.vafer%22%20AND%20a%3A%22jdeb%22

**Comment by tcurdt** [comment] 2015-02-28 18:26
Thanks for checking.

**Comment by rfletcher** [comment] 2015-04-08 16:06
Revisited this today and I have a little more information for you:

1.   `<controlDir/>` can't be set in an execution-specific `<configuration/>` (as in my example above), but it *can* be set at the `<plugin><configuration/></plugin>` level. In fact, nothing but `<dataSet/>` seems to work for me in execution-level configuration. I end up with default values instead.
2.   `${baseDir}` isn't being expanded, so even when setting `controlDir` at the plugin level, it's looking for a literal `'${baseDir}/foo/bar'` directory.
    
    In the case of baseDir-relative paths, using the format defined internally (`"[[baseDir]]/foo/bar"`) works as a workaround. As does a relative path (`"foo/bar"`).
    
    This must be the cause of the original "doesn't point to a directory" error.

Hope that helps.

**Comment by hohwille** [comment] 2015-05-07 16:39
I did ran into the same problem and adding a ```<configuration>``` section outside the ```<executions>``` with the control config helps as a workaround.

I did create the effective POM with ```mvn help:effective-pom``` and discovered that there is an additional execution added with id ```default-jdeb``` this goes away if I use exactly this id in my configuration. Maybe this has something to do with the problem (and maybe not)...

**Comment by rafalwrzeszcz** [comment] 2016-01-08 12:53
`${baseDir}` is not a proper Maven project property I think, it should be `${project.basedir}`. The setting works for me (1.4)

**Comment by rfletcher** [comment] 2016-01-08 16:47
> ${baseDir} is not a proper Maven project property

It is a supported property. At some point it was deprecated in favor of `${project.basedir}`, but `${baseDir}` is still supported according to the [latest Maven 3.x docs](http://maven.apache.org/components/ref/3-LATEST/maven-model-builder/).

**Comment by tcurdt** [comment] 2016-01-16 01:38
Sorry, folks - I cannot reproduce any of this. [Even the example](https://github.com/tcurdt/jdeb/blob/master/src/examples/maven/pom.xml#L30) explicitly uses `${baseDir}` and builds just fine for me.

    Apache Maven 3.0.4 (r1232337; 2012-01-17 09:44:56+0100)
    Maven home: /Users/tcurdt/Library/Java/mvn
    Java version: 1.8.0_66, vendor: Oracle Corporation
    Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/jre
    Default locale: en_US, platform encoding: UTF-8
    OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"

**Comment by tcurdt** [comment] 2016-01-16 01:39
If someone can provide a test case to reproduce this I am happy to revisit. At least we have improved the error message to include the path. Closing for now. Please raise again if you run into this again.

**Closed by tcurdt** 2016-01-16 01:39 UTC
Labels: bug

**Comment by rfletcher** [comment] 2016-01-16 01:45
The example works for me too, but change the jdeb `<version/>` from 1.4 to 1.3 and it fails. It appears the bug was unknowingly fixed in 1.4.

**Comment by rfletcher** [comment] 2016-01-16 02:47
I've [forked the repo](https://github.com/rfletcher/jdeb/tree/issue-178) and modified the example to reproduce the bug. I could only reproduce it when:

1. the build produces a .deb artifact (9640d1886fc88b999a8fd4705e588153340be95f)
2. the control dir is something other than the default (656d9571c45f78da01844694a4748f6de2b58bdb)

If I revert either one of those commits the build succeeds, but with both of them present it fails with the original error:

````
...
[INFO] --- jdeb:1.4:jdeb (default-jdeb) @ jdeb-example ---
[ERROR] Failed to create debian package /Users/rick/Code/third-party/jdeb/src/examples/maven/target/jdeb-example_1.0~SNAPSHOT_all.deb
org.vafer.jdeb.PackagingException: The 'control' attribute doesn't point to a directory.
	at org.vafer.jdeb.DebMaker.validate(DebMaker.java:220)
...
````

The diffs are small enough that I don't think I've done anything to legitimately break the path. Let me know if you still can't reproduce it, but I hope this finally does it!

**Comment by tcurdt** [comment] 2016-01-16 03:18
Thanks, for digging deeper, @rfletcher - but when you point jdeb to a non existent directory - of course it will fail. And latest master (and soon 1.5) will also tell you the path. If you change `deb` to `foo` you also need to rename the dir and dataset path.

**Comment by rfletcher** [comment] 2016-01-16 03:22
It exists. The `control` file was moved from `.../deb/...` to `.../foo/...` in the [second commit](https://github.com/tcurdt/jdeb/commit/656d9571c45f78da01844694a4748f6de2b58bdb) referenced above.  I left the `init.d` dir beneath `.../deb/...`, so the path in the dataset shouldn't need to change.

**Comment by tcurdt** [comment] 2016-01-16 03:27
Sorry, I missed the rename in the commit.
Odd - I just renamed the `deb` to `foo`, change the property and it works just fine over here.
Let me try your fork.

As for the different packaging - that's totally different issue.
I've never seen jdeb use like that before. I assume that maven calls the plugin in a different phase and we might not have any (but the default) configuration at all then. Maybe check with `mvn -X`.

**Comment by rfletcher** [comment] 2016-01-16 03:30
> As for the different packaging - that's totally different issue. I've never seen jdeb use like that before.

No kidding? I'm not sure where I got that from. I'm definitely not enough of a Maven expert to have whipped it up myself. It's definitely part of the problem. Like I said, I can only reproduce it when configured that way.

**Comment by rfletcher** [comment] 2016-01-16 03:32
Adding `-X` shows me the same (default) property values as the original bug report, including:

````
[DEBUG]   (f) controlDir = [[baseDir]]/src/deb/control
````

**Comment by tcurdt** [comment] 2016-01-16 03:41
Also with your fork: Works as expected - unless you use the `deb` artifact packaging. The issues are not really connected.

I have the theory that when maven is calling it does have any configuration at all. I assume you are just attaching it to the lifecycle phase without further configuration.

I agree it would be nice being able to use packaging as `deb` but I guess it would need some more maven digging to get this working.

**Comment by rfletcher** [comment] 2016-01-16 03:52
Yeah, differences in extension vs. plugin loading is well beyond my Maven knowledge.

[As mentioned](#issuecomment-90960944) further up, if the `<configuration/>` block is at the `<plugin/>` level instead of the `<execution/>` level, deb packaging works just fine. That the workaround I've been using. I'll just leave it in place.

Thanks for investigating.

**Comment by akkishah1993** [comment] 2022-04-01 10:10
Hi Folks,

I am using the same plugin to package my spring boot application as a debian package. I am getting an error. I have put the configuration tag at plugin level only still it is not working. Below is my code and also attached an error. Thanks in advance.


![2](https://user-images.githubusercontent.com/15965171/161243313-17a76f3b-afee-4a5c-a5e4-133ef9471869.PNG)
![1](https://user-images.githubusercontent.com/15965171/161243318-ed0df0b6-716f-4ac9-9aa1-b63e2218bdf4.png)
![3](https://user-images.githubusercontent.com/15965171/161243526-bd0d7e24-639e-4391-a9ea-27d2fdb35c29.PNG)
