### ISSUE TITLE
Incorrect version string, injects a "~" after "o" in version.

### ISSUE THREAD

**Issue by bedge** [tcurdt/jdeb#210] opened 2015-05-18 17:46 UTC
This is truly odd. I have a build version="3.45.0-obelix-98"

I'm getting packages named: target-content_3.45.0+o~belix+98_all.deb
                              expected: target-content_3.45.0+obelix+98_all.deb

with similar dependencies: Depends: nim-target-cb (>=3.45.0+o~belix+98)
                           expected: Depends: nim-target-cb (>=3.45.0+obelix+98)

**Comment by bedge** [comment] 2015-05-18 18:08
Seems to be triggered with a "-o".

using "-ao" doesn't trigger this behavior.

Here's a sample output:

```
[INFO] --- jdeb:1.4:jdeb (default) @ nim-cluster-aws ---
[INFO] Creating debian package: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb
[INFO] Building conffiles
[INFO] Adding conffile: etc/slurm-llnl/slurm.conf
[INFO] Adding conffile: etc/munge/munge.key
[INFO] Adding conffile: etc/init.d/nodemonitor
[INFO] Creating changes file: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.changes
[INFO] Attaching created debian package /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ nim-cluster-aws ---
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws-3.45.0-obelix-98.jar to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/nim-cluster-aws-3.45.0-obelix-98.jar
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/nim-cluster-aws-3.45.0-obelix-98.pom
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/nim-cluster-aws-3.45.0-obelix-98.deb
```

and again using "-bo"

```
[INFO] --- jdeb:1.4:jdeb (default) @ nim-cluster-aws ---
[INFO] Creating debian package: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0~bobelix+98_all.deb
[INFO] Building conffiles
[INFO] Adding conffile: etc/slurm-llnl/slurm.conf
[INFO] Adding conffile: etc/munge/munge.key
[INFO] Adding conffile: etc/init.d/nodemonitor
[INFO] Creating changes file: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0~bobelix+98_all.changes
[INFO] Attaching created debian package /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0~bobelix+98_all.deb
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ nim-cluster-aws ---
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws-3.45.0-bobelix-98.jar to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-bobelix-98/nim-cluster-aws-3.45.0-bobelix-98.jar
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-bobelix-98/nim-cluster-aws-3.45.0-bobelix-98.pom
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0~bobelix+98_all.deb to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-bobelix-98/nim-cluster-aws-3.45.0-bobelix-98.deb
```

**Comment by bedge** [comment] 2015-05-18 18:29
Here's an filtered for brevity (grep  belix) mvn -X output. 

The last few lines is the first place the new version string pops up:

```
[DEBUG] Extension realms for project com.nim.ct:nim-cluster-aws:jar:3.45.0-obelix-98: [ClassRealm[extension>org.apache.maven.wagon:wagon-ssh-external:2.6, parent: sun.misc.Launcher$AppClassLoader@6bd46c20]]
[DEBUG] Created new class realm project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG] Populating class realm project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG] Looking up lifecyle mappings for packaging jar from ClassRealm[project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Project: com.nim.ct:nim-cluster-aws:jar:3.45.0-obelix-98
[INFO] Building NIM AWS cluster configuration 3.45.0-obelix-98
[DEBUG] Project:       com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG] com.nim.ct:nim-cluster-aws:jar:3.45.0-obelix-98
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[INFO] Deleting file /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb
[INFO] Deleting file /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws-3.45.0-obelix-98.jar
[INFO] Deleting file /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.changes
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (f) project = MavenProject: com.nim.ct:nim-cluster-aws:3.45.0-obelix-98 @ /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (f) project = MavenProject: com.nim.ct:nim-cluster-aws:3.45.0-obelix-98 @ /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (f) outputFileName = nim-cluster-aws-3.45.0-obelix-98
[DEBUG]   (f) projectArtifact = com.nim.ct:nim-cluster-aws:jar:3.45.0-obelix-98
[DEBUG]   (f) project = MavenProject: com.nim.ct:nim-cluster-aws:3.45.0-obelix-98 @ /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml
[DEBUG]   (f) outputFileName = nim-cluster-aws-3.45.0-obelix-98
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (s) project = MavenProject: com.nim.ct:nim-cluster-aws:3.45.0-obelix-98 @ /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (f) finalName = nim-cluster-aws-3.45.0-obelix-98
[DEBUG]   (f) project = MavenProject: com.nim.ct:nim-cluster-aws:3.45.0-obelix-98 @ /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml
[DEBUG] isUp2date: false (Destination /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws-3.45.0-obelix-98.jar not found.)
[INFO] Building jar: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws-3.45.0-obelix-98.jar
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (f) project = MavenProject: com.nim.ct:nim-cluster-aws:3.45.0-obelix-98 @ /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml
[INFO] Creating debian package: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb
[INFO] Creating changes file: /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.changes
[INFO] Attaching created debian package /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb
[DEBUG]   Imported:  < project>com.nim.ct:nim-cluster-aws:3.45.0-obelix-98
[DEBUG]   (f) artifact = com.nim.ct:nim-cluster-aws:jar:3.45.0-obelix-98
[DEBUG]   (f) attachedArtifacts = [com.nim.ct:nim-cluster-aws:deb:3.45.0-obelix-98]
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws-3.45.0-obelix-98.jar to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/nim-cluster-aws-3.45.0-obelix-98.jar
[DEBUG] Writing resolution tracking file /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/_maven.repositories
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/pom.xml to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/nim-cluster-aws-3.45.0-obelix-98.pom
[DEBUG] Writing resolution tracking file /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/_maven.repositories
[INFO] Installing /var/lib/jenkins/git/server/content/sdk/nim-cluster-aws/target/nim-cluster-aws_3.45.0+o~belix+98_all.deb to /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/nim-cluster-aws-3.45.0-obelix-98.deb
[DEBUG] Writing resolution tracking file /var/lib/jenkins/.m2/repository/com/nim/ct/nim-cluster-aws/3.45.0-obelix-98/_maven.repositories
```

target dir:
```
0 %> ls -l target
total 28
drwxr-xr-x 2 jenkins nogroup  4096 May 18 11:25 maven-archiver
-rw-r--r-- 1 jenkins nogroup   797 May 18 11:25 nim-cluster-aws_3.45.0+o~belix+98_all.changes
-rw-r--r-- 1 jenkins nogroup 11112 May 18 11:25 nim-cluster-aws_3.45.0+o~belix+98_all.deb
-rw-r--r-- 1 jenkins nogroup  2009 May 18 11:25 nim-cluster-aws-3.45.0-obelix-98.jar
```

**Comment by jglogan** [comment] 2015-05-18 20:15
It may be that the problem is in this bit of Utils.java:

private static final Pattern BETA_PATTERN = Pattern.compile("(.*?)([\\.\\-_]?)(alpha|a|beta|b|milestone|m|cr|rc)(.*)", Pattern.CASE_INSENSITIVE);

Could you try naming the pattern to something like 'ocelot' and try again?

**Comment by bedge** [comment] 2015-05-18 20:36
ocelot = ok
ocelox = ok
ocelix = ok
oaelix = fail
obilix = fail

**Comment by jglogan** [comment] 2015-05-18 20:39
Using an online regex tester with the above pattern and your version string yields:
0: [7,10] obe
1: [7,8] o
2: [8,8]
3: [8,9] b
4: [9,10] e
The replacement drops match.group(2), so the behavior you're seeing is expected given the code.

**Comment by bedge** [comment] 2015-09-30 21:45
Amy update on this? I find I'm having to rename other peoples branches to work around it. There's a lot of things that trip the failure case.

**Comment by tcurdt** [comment] 2015-09-30 23:17
@bedge looks like we need to fix the regex handling.
More than happy to accept a patch for that and then do a new release soon.

**Comment by bedge** [comment] 2015-09-30 23:26
The problem seems to be the un-anchored single characters.
```
(.?)([\.\-_]?)(alpha|a|beta|b|milestone|cr|rc)(.)
```
How about using this:
```
(.?)([\.\-_]?)(alpha|beta|milestone|cr|rc)(.)
```

**Comment by tcurdt** [comment] 2015-09-30 23:37
Well, we cannot just drop `a` and `b`.

**Comment by bedge** [comment] 2015-10-01 11:28
The problem we're running into is that we use branch names as part of our version string, ie:
`<base version>-<branch>-<build number>`
iow
`1.2.3-branch-123`
So the fact that we're matching the `BETA_PATTERN` at all is entirely accidental.

**Comment by tcurdt** [comment] 2015-10-01 18:50
@bedge I think the regex is just wrong

I think a good way forward would be to define all expectations in a test case and then work on the regex until the test passes all expectations.

**Comment by bedge** [comment] 2015-10-02 05:38
I did a bit of poking around and the standard debian tools don't treat any of the "upstream-version" string specially.
The deb-version source uses: `[epoch:]upstream-version[-debian-revision]`

lintian has: `our $PKGNAME_REGEX = qr/[a-z0-9][-+\.a-z0-9]+/o;`

Maven *https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN401) says: "Identical versions with different qualifier fields are compared by using basic string comparison." So no special treatment there either.

So I'm not sure where the `"(.?)([\.\-_]?)(alpha|a|beta|b|milestone|m|cr|rc)(.)"` came from. However I can understand that you wouldn't want to yank that with no warning when someone is undoubtedly  counting on it.

How about delineating the "magic" (`alpha|a|beta|b|milestone|m|cr|rc`) strings with a word boundary, `\b`? That would make the intent more explicit as the \y wouldn't match substrings, ie:
`(.?)([\.\-_]?)\b(alpha|a|beta|b|milestone|m|cr|rc)\b(.)`
Note the `\b` bracketing the magic strings.

This means that `1.2.3-alpha-x-123` still matches as:
1.	[4-5]	`3`
2.	[5-6]	`-`
3.	[6-11]	`alpha`
4.	[11-12]	`-`

As do all `alpha|a|beta|b|milestone|m|cr|rc` variants, and `1.2.3-obelix-123` is unaffected as the `b` is not a `word` in the regex sense.

**Comment by ebourg** [comment] 2015-10-02 08:01
Some background information on the current implementation: the sorting algorithm in Debian ranks `1.0-beta-1` after `1.0`, so if you publish a beta version to your APT repository with this scheme, you can't later publish a 1.0 version since apt will think it's an older version. That's why the alpha, beta, etc patterns are detected and replaced by `1.0~beta-1`.

**Comment by tcurdt** [comment] 2015-10-10 10:29
We certainly could move the "magic" out of the pattern matching (and instead just extract the words). This is a big change though. I really think creating a proper test case for all the various/supported combinations should be the first step.

**Comment by tmortagne** [comment] 2015-12-29 10:02
Committed an idea in a branch. Basically the idea is to make sure we match beta pattern only when there is no [a-z] before and after it.

**Comment by tcurdt** [comment] 2015-12-29 10:20
@tmortagne but doesn't that sound a bit like adding more magic rather than reducing it?

Let's update the [test case](https://github.com/tcurdt/jdeb/blob/master/src/test/java/org/vafer/jdeb/utils/UtilsTestCase.java#L117) to cover all corner cases we can come up with and then try to iterate there.

**Comment by tmortagne** [comment] 2015-12-29 10:28
That's exactly what I did, I added more use case to the already big test case and improved the regex to make all of them pass.

**Comment by tcurdt** [comment] 2015-12-29 10:39
(y)

**Closed** 2015-12-30 11:19 UTC
Labels: bug

**Comment by bedge** [comment] 2016-01-23 03:27
Any ETA on a new release to include this fix?

**Comment by tcurdt** [comment] 2016-01-23 07:50
@bedge we are very close on the release of 1.5. I hope end of the month.
