### ISSUE TITLE
Field length limit of 100 - possible to extend?

### ISSUE THREAD

**Issue by fredcooke** [tcurdt/jdeb#241] opened 2016-08-26 07:29 UTC
I misconfigured my properties because I'm a little rusty with Maven setup - I used basedir for my own purpose and it got overridden and ended up being used for all symlinks and targets which made for a long target and long link path/name.

Is the 100 character limit necessary? From where does it come? I don't think file system target limits are this short... but maybe the archive format that Deb uses is the restriction?

Output, sanitised:

Caused by: java.lang.IllegalArgumentException: Field '/home/fred/repos/blah/blah/blah/etc' too long, maximum is 100

If there's a legit reason for this, a better message would be nice explaining to mere mortals why 100 is too much.

**Comment by tcurdt** [comment] 2016-08-26 08:55
Please provide a stacktrace so one can see where that exception originated from.

**Comment by fredcooke** [comment] 2016-08-26 09:18
`[INFO] Creating debian package: /home/fred/repos/<snip>t_0.1~SNAPSHOT_all.deb
[ERROR] Failed to create debian package /home/fred/repos/<snip>_0.1~SNAPSHOT_all.deb
org.vafer.jdeb.PackagingException: Failed to create debian package /home/fred/repos/<snip>_0.1~SNAPSHOT_all.deb
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:333)
	at org.vafer.jdeb.maven.DebMojo.execute(DebMojo.java:567)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:622)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.vafer.jdeb.PackagingException: Could not create deb package
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:554)
	at org.vafer.jdeb.DebMaker.createDeb(DebMaker.java:448)
	at org.vafer.jdeb.DebMaker.makeDeb(DebMaker.java:329)
	... 22 more
Caused by: java.lang.IllegalArgumentException: Field '/home/fred/repos/<snip>' too long, maximum is 100
	at org.vafer.jdeb.DataBuilder.checkField(DataBuilder.java:70)
	at org.vafer.jdeb.DataBuilder.access$100(DataBuilder.java:43)
	at org.vafer.jdeb.DataBuilder$1.onEachLink(DataBuilder.java:166)
	at org.vafer.jdeb.producers.DataProducerLink.produce(DataProducerLink.java:57)
	at org.vafer.jdeb.maven.Data.produce(Data.java:165)
	at org.vafer.jdeb.DataBuilder.buildData(DataBuilder.java:259)
	at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:470)
	... 24 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
`

**Comment by tcurdt** [comment] 2016-08-26 09:39
As you can see from the stack trace the check is done [here](https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DataBuilder.java#L167)

```
                checkField(entry.getLinkName(), TarConstants.NAMELEN);
                checkField(entry.getUserName(), TarConstants.UNAMELEN);
                checkField(entry.getGroupName(), TarConstants.GNAMELEN);
```

So unless the constants are invalid in commons compress these are the maximums as defined by `tar` itself.

**Comment by fredcooke** [comment] 2016-08-26 09:57
Thanks! A quick look of the inevitably accurate wikipedia page shows that those might be worst case for old tar, which is not what Debian based systems use. Perhaps commons compress doesn't do GNU or is being used wrongly? Seems pretty restrictive, though once I fixed by bad variable it was a non issue. Only reporting it to try to help improve the already amazing and awesome jdeb :-) 

https://en.wikipedia.org/wiki/Tar_%28computing%29#POSIX.1-2001.2Fpax
https://en.wikipedia.org/wiki/Tar_%28computing%29#GNU

**Comment by fredcooke** [comment] 2016-08-26 10:05
https://commons.apache.org/proper/commons-compress/examples.html

"Commons Compress 1.3 also optionally supports writing archives with file names longer than 16 characters using the BSD dialect, writing the SVR4/GNU dialect is not supported."

Commons compress limitation in AR archive support. Not sure what else is available that can do what's required, however it certainly seems that it's possible to exceed this limitation if anyone else ever hits it.

**Comment by tcurdt** [comment] 2016-08-26 10:18
Thanks for investigating this.

> Commons Compress 1.0 to 1.2 can only read archives using the GNU/SRV4 variant, support for the BSD variant has been added in Commons Compress 1.3. Commons Compress 1.3 also optionally supports writing archives with file names longer than 16 characters using the BSD dialect, writing the SVR4/GNU dialect is not supported.

That sounds a little odd. The original AR implementation was from me/jdeb. So writing was always a concern since Commons Compress 1.0. I am also one of the commons compress committers - but I don't think I will find the time to look at this in detail at the moment.

**Comment by fredcooke** [comment] 2016-08-26 10:54
My pleasure! I've been providing feedback since 0.8 or something like that :-) I love jdeb! And this is not affecting me, I just stumbled upon it. So I guess just leave it open and deal with it if you feel like it in future. <3

**Comment by tcurdt** [comment] 2018-01-02 23:50
Actually - the `AR` part is irrelevant. The files are stored in a `tar` in an `ar` - and the `tar` is giving the exception. The relevant information is here:

  https://commons.apache.org/proper/commons-compress/tar.html

The longFileMode option of TarArchiveOutputStream controls how files with names longer than 100 characters are handled. The possible choices are:

> - LONGFILE_ERROR: throw an exception if such a file is added. This is the default.
> - LONGFILE_TRUNCATE: truncate such names.
> - LONGFILE_GNU: use a GNU tar variant now refered to as "oldgnu" of storing such names. If you choose the GNU tar option, the archive can not be extracted using many other tar implementations like the ones of OpenBSD, Solaris or MacOS X.
> - LONGFILE_POSIX: use a PAX extended header as defined by POSIX 1003.1. Most modern tar implementations are able to extract such archives. since Commons Compress 1.4
> TarArchiveInputStream will recognize the GNU tar as well as the POSIX extensions (starting with Commons Compress 1.2) for long file names and reads the longer names transparently.

So I guess we just need to figure out what is supported in `deb`s. `GNU`? `POSIX`?

**Comment by tcurdt** [comment] 2018-01-03 08:36
From https://manpages.debian.org/testing/dpkg-dev/deb.5.en.html

> The tar archives currently allowed are, the old-style (v7) format, the pre-POSIX ustar format, a subset of the GNU format (new style long pathnames and long linknames, supported since dpkg 1.4.1.17; large file metadata since dpkg 1.18.24), and the POSIX ustar format (long names supported since dpkg 1.15.0). Unrecognized tar typeflags are considered an error. Each tar entry size inside a tar archive is limited to 11 ASCII octal digits, allowing for up to 8 GiB tar entries. The GNU large file metadata support permits 95-bit tar entry sizes and negative timestamps, and 63-bit UID, GID and device numbers.

**Comment by tcurdt** [comment] 2018-01-03 15:59
So it turns out `jdeb` already supports switching to POSIX style - we just default to `GNU`. See `DebMaker`.

```
    /**
     * Sets the long file mode for the resulting tar file.  Valid values are "gnu", "posix", "error" or "truncate"
     * @see org.apache.commons.compress.archivers.tar.TarArchiveOutputStream#setLongFileMode(int)
     */
    @Parameter(defaultValue = "gnu")
    private String tarLongFileMode;

```
So I think it's safe to say we can close this issue now.
It would be good to investigate whether `posix` should be the default style though.

**Closed by tcurdt** 2018-01-03 15:59 UTC
Labels: improvement

**Comment by fredcooke** [comment] 2018-01-03 20:31
Thanks for your time on this! Appreciate it! :-)

**Comment by tcurdt** [comment] 2018-04-27 22:32
@chali well, looking at the code I see the string being passed to the `TarOptions` here

  https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DebMaker.java#L487

and there it being set to the equivalent Commons Compress value

  https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/TarOptions.java#L18

I would suggest to either debug this or even better to create a testcase that replicates the problem.
Right now I don't see anything wrong in `jdeb` itself from looking at the sources.

**Comment by chali** [comment] 2018-04-27 22:48
Here is what I'm doing which fails for me https://github.com/chali/directoryNameRegression/blob/master/too_long_link/src/test/groovy/cz/chali/jdep/TooLongLinkSpec.groovy

**Comment by chali** [comment] 2018-04-30 23:06
The exception is from this place: https://github.com/tcurdt/jdeb/blob/jdeb-1.6/src/main/java/org/vafer/jdeb/DataBuilder.java#L172. I haven't found how the check is affected  or disabled by `maker.setTarLongFileMode('posix')`.
