### ISSUE TITLE
Issue in Date field

### ISSUE THREAD

**Issue by yobslob** [tcurdt/jdeb#713] opened 2024-07-07 14:20 UTC
The `.changes` files are not progressive because the `ChangesFileBuilder` is not using the `outputTimestamp` argument to change the Date field. Therefore,  each .changes file can vary depending on when it is created, leading to inconsistencies and a lack of version control.
Hope it helps.

**Comment by tcurdt** [comment] 2024-07-07 14:52
duplicate of https://github.com/tcurdt/jdeb/issues/712

**Closed by tcurdt** 2024-07-07 14:52 UTC
