### ISSUE TITLE
missing leading slash when set a single file data as conffile

### ISSUE THREAD

**Issue by cvgaviao** [tcurdt/jdeb#227] opened 2016-01-18 03:52 UTC
if a conffiles is not provided and a file data has a <conffile> parameter then one will be generated.
But the generated item inside the file in this case has missing leading slash even if the prefix has it. 
```
    <data>
        <src>${project.build.outputDirectory}/config/default-node.txt</src>
	<type>file</type>
	<dst>${deb.conf.name}</dst>
	<conffile>true</conffile>
	<mapper>
	<type>perm</type>
	<prefix>/etc/lunifera</prefix>
	</mapper>
    </data>
```
This is the message in the console:
```
    [INFO] Building conffiles
    [INFO] Adding conffile: etc/lunifera/default.xargs
```
and also the Lintian generates the error bellow:
```
    relative-conffile etc/lunifera/default.xargs
```

**Comment by tcurdt** [comment] 2016-01-18 10:17
That's a duplicate of https://github.com/tcurdt/jdeb/issues/217

**Closed by tcurdt** 2016-01-18 10:17 UTC
